#!/usr/bin/env python3

from scocket import *
import time

time = time.time()

def Scan(targetIP):
    host = gethostbyname(targetIP)
    print('Scanning...',host)
    
    for i in range(1, 500):
        socket = socket(AF_INET, SOCK_STREAM)
    
        connect = socket.connect_ex((host, i))
        if(connect == 0)
            print('Port %d: [OPEN]')
        socket.close()
    
    print('time = ' time.time() - time)

if __name__ == '__main__':
    targetIP = input('Enter IP:')
